apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: sdks-test
spec:
  className: dir-spire
  podSelector:
    matchExpressions:
      - key: batch.kubernetes.io/job-name
        operator: In
        values:
          - sdks-test
  spiffeIDTemplate: {{ "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}" }}
  autoPopulateDNSNames: true