# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.discovery.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime.discovery.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime.discovery.labels" . | nindent 4 }}
  {{- with .Values.discovery.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
