# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.server.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runtime.server.fullname" . }}
  labels:
    {{- include "runtime.server.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "runtime.server.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "runtime.server.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
