# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.server.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "runtime.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime.server.labels" . | nindent 4 }}
data:
  server.config.yml: |
    {{- $config := deepCopy .Values.server.config }}
    {{- if .Values.etcd.enabled }}
    {{- $_ := set $config.store.etcd "host" (include "runtime.etcd.fullname" .) }}
    {{- $_ := set $config.store.etcd "port" (.Values.etcd.service.port | int) }}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
{{- end }}
