# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "runtime.server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime.server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
      {{- if and (eq .Values.server.service.type "NodePort") .Values.server.service.nodePort }}
      nodePort: {{ .Values.server.service.nodePort }}
      {{- end }}
  selector:
    {{- include "runtime.server.selectorLabels" . | nindent 4 }}
{{- end }}
