{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "envoy-authz.fullname" . }}-envoy
  labels:
    {{- include "envoy-authz.envoyLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      {{- include "envoy-authz.envoySelector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-envoy.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "envoy-authz.envoySelector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "envoy-authz.envoyServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: envoy
        image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
        imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        {{- if .Values.envoy.admin.enabled }}
        - name: admin
          containerPort: {{ .Values.envoy.admin.port }}
          protocol: TCP
        {{- end }}
        command:
        - /usr/local/bin/envoy
        - -c
        - /etc/envoy/envoy.yaml
        - --service-cluster
        - {{ include "envoy-authz.fullname" . }}
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
          readOnly: true
        {{- if .Values.envoy.spiffe.enabled }}
        - name: spiffe-workload-api
          mountPath: /run/spire/agent-sockets
          readOnly: true
        {{- end }}
        livenessProbe:
          httpGet:
            path: /ready
            port: admin
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: admin
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.envoy.resources | nindent 10 }}
      volumes:
      - name: envoy-config
        configMap:
          name: {{ include "envoy-authz.fullname" . }}-envoy-config
      {{- if .Values.envoy.spiffe.enabled }}
      - name: spiffe-workload-api
        csi:
          driver: csi.spiffe.io
          readOnly: true
      {{- end }}
