{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy-authz.serviceAccountName" . }}
  labels:
    {{- include "envoy-authz.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
# Separate service account for Envoy (for SPIFFE ID)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy-authz.envoyServiceAccountName" . }}
  labels:
    {{- include "envoy-authz.envoyLabels" . | nindent 4 }}
{{- end }}
