{{- if eq .Values.spire.enabled true }}
# ClusterSPIFFEID for reconciler workload
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: {{ include "chart.reconcilerName" . }}
spec:
  className: {{ .Values.spire.className | default (printf "%s-spire" .Release.Namespace) }}
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: In
      values:
      - reconciler
  workloadSelectorTemplates:
    - k8s:pod-image:{{ .Values.reconciler.image.repository }}:{{ .Values.reconciler.image.tag }}
    - k8s:sa:{{ include "chart.serviceAccountName" . }}
  spiffeIDTemplate: {{ "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}" }}
  autoPopulateDNSNames: true
  {{- if .Values.spire.federation }}
  federatesWith:
  {{ range .Values.spire.federation }}
    - {{ .trustDomain }}
  {{ end }}
  {{- end }}
{{- end }}
