# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Project

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  sync-items:
    name: Sync items
    runs-on: ubuntu-latest
    steps:
      - name: Sync stale items
        uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008 # v10.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 90
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: no-stale
          exempt-pr-labels: no-stale
          stale-issue-message: >
            Thank you for your contribution! This issue has been automatically
            marked as `stale` because it has no recent activity in the last
            60 days. It will be closed in 90 days, if no further activity
            occurs. If this issue is still relevant, please leave a comment to
            let us know, and the `stale` label will be automatically removed.
          stale-pr-message: >
            Thank you for your contribution! This PR has been automatically
            marked as `stale` because it has no recent activity in the last
            60 days. It will be closed in 90 days, if no further activity occurs.
            If this pull request is still relevant, please leave a comment to 
            let us know, and the `stale` label will be automatically removed.
          close-issue-message: >
            This issue has been marked `stale` for 90 days, and is now closed
            due to inactivity. If the issue is still relevant, please re-open
            this issue or file a new one. Thank you!
          close-pr-message: >
            This PR has been marked `stale` for 90 days, and is now closed
            due to inactivity. If this contribution is still relevant, please
            re-open this PR or file a new one. Thank you!

  sync-labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout labels
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          sparse-checkout: .github/labels.yml

      - name: Sync labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          dry-run: false
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
          delete-other-labels: false
