# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

name: Release Helm

on:
  workflow_dispatch:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
        default: "ghcr.io/agntcy"
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."
  workflow_call:
    inputs:
      image_repo:
        required: true
        type: string
        description: "Image repo to use."
      release_tag:
        required: true
        type: string
        description: "Release tag for all components."
      chart_path:
        required: false
        type: string
        description: "Chart path component (e.g., 'dir' or 'dir-dev'). Defaults to 'dir'."
        default: "dir"

jobs:
  chart:
    name: Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: [dir, dirctl]
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: notused
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1

      - name: Helm update
        shell: bash
        run: helm dependency update install/charts/${{ matrix.chart }}

      - name: Helm lint
        shell: bash
        run: helm lint install/charts/${{ matrix.chart }} --with-subcharts

      - name: Helm package
        id: build
        shell: bash
        run: |
          helm package install/charts/${{ matrix.chart }} --dependency-update --version ${{ inputs.release_tag }}
          echo "package=${{ matrix.chart }}-${{ inputs.release_tag }}.tgz" >> "$GITHUB_OUTPUT"

      - name: Helm push to GHCR OCI registry
        shell: bash
        run: |
          CHART_PATH="${{ inputs.chart_path || 'dir' }}/helm-charts"
          echo "ðŸš§ Pushing ${{ steps.build.outputs.package }} to GHCR OCI registry"
          echo "Chart path: ${CHART_PATH}"
          helm push ${{ steps.build.outputs.package }} oci://${{ inputs.image_repo }}/${CHART_PATH}
